# Generated by Django 6.0.7 on 2026-07-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
